### ISSUE TITLE
More customizable GUI

### ISSUE THREAD

**Issue by RollexGrief** [stijnb1234/VehiclesPlus#46]
I would like to be able to customize GUI everything as users want it

Describe alternatives you've considered
Changing items, gui sizes, in general, full customization

Additional context
I don't have any additional context.

**Comment by stijnb1234** [comment]
Full customization is something I don't see happening anytime soon, because that also makes setup more difficult. I'm going to try to make as much configurable as possible in the recode, but GUI sizes etc. won't be there anytime soon.

**Comment by RollexGrief** [comment]
Anyway, thanks for the answer.
