### ISSUE TITLE
Vehicles not saved when game rejoined

### ISSUE THREAD

**Issue by MarioFoli** [stijnb1234/VehiclesPlus#51]
**Is your feature request related to a problem? Please describe.**  
When logging out of the server soon after upgrading a vehicle, it does not save that vehicle upgrade.

**Describe the solution you'd like**  
A configuration option / fix to increase the interval vehicle upgrades are saved at.

**Comment by relavis** [comment]
After some testing, it appears that the vehicle will only be saved correctly if:

1. The player leaves the server
2. The player does not rejoin the server until the server has stopped or restarted

**Comment by stijnb1234** [comment]
This problem will not be solved until the recode, because in the recode the storage system will be completely recoded.
