### ISSUE TITLE
Custom Speedvalue for Vehicles

### ISSUE THREAD

**Issue by ExCorde** [stijnb1234/VehiclesPlus#54]
I would be pleased if there was a feature that adds the following: 
- A Setting where you can expand or damp the speed value.

Example: On my roads, there is 70km/h allowed. But when you drive 70km/h it's way too fast, because 70km/h in Vehicles Plus seems to be 130km/h in Minecraft. I would like a feature, where I can manipulate the speed display of a vehicle that it's the same speed in Minecraft, but higher speed on the tachometer. I don't know if you understood my wish, because it's so difficult to describe.

**Comment by ExCorde** [comment]
It would look weird if I make 50km/h signs for a wide well-built highway road, only because it has small curves.

**Comment by stijnb1234** [comment]
Please use the API for this.
