### ISSUE TITLE
Fake (model) vehicles

### ISSUE THREAD

**Issue by SatireShadow** [stijnb1234/VehiclesPlus#58]
Model vehicles would be a vehicle that you can spawn that already has tires and everything else that will be just that a model. No one can drive it or do anything to it but its just there meant to display what cars/planes/boats look like. I'm not sure if this is the correct place to put this but I was told on discord to make one here.

**Comment by stijnb1234** [comment]
Please use armorstands for this. You can use the /minecraft:get command to get your model, and then put it on the head of the armorstand to show it somewhere.
