### ISSUE TITLE
Bike issues.

### ISSUE THREAD

**Issue by SatireShadow** [stijnb1234/VehiclesPlus#77]
**Describe the bug**  
When you get off a bike and it isn't fully level you cannot reenter it and are stuck with it just sitting there.

**To Reproduce**  
1. Spawn a bike
2. Ride around
3. Jump off

**Expected behavior**  
It is expected to auto level or just say in place but allow reentry.

**Screenshots or Video Recordings**  
https://youtu.be/DFZ3XboNksM

**Server and Plugin Information**
 - Installed plugins: alot
 - VehiclesPlus Version: 2.2.5
 - Pro or Lite? pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: Paper 1.16.5
 - Operating System (if applicable): Java 11

**Additional context**  
Add any other context about the problem here, server timings reports, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by stijnb1234** [comment]
Can you include the error you get?

**Comment by SatireShadow** [comment]
> Can you include the error you get?

No errors, nothing just you know does that.

**Comment by SatireShadow** [comment]
Any news?

**Comment by stijnb1234** [comment]
Please change the exitWhileMoving setting to true. This is a bug in Minecraft 1.16, which is already fixed in 1.17.
