### ISSUE TITLE
Seperate Garages

### ISSUE THREAD

**Issue by SatireShadow** [stijnb1234/VehiclesPlus#89]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. Ex. I'm always frustrated when I am setting up an area to spawn cars and players through this can spawn airplanes, boats, and helicopters making it really hard for roleplay.

**Describe the solution you'd like**  
A clear and concise description of what you want to happen. A separate garage menu whether it be you can select what spawns in a specific command or its based on types so /v helipad /v boatdock /v hanger and also have /v forcehanger commands

**Describe alternatives you've considered**  
A clear and concise description of any alternative solutions or features you've considered. I considered making my own custom commands for it but it seems way out of my league and over complicated.

**Additional context**

**Comment by stijnb1234** [comment]
I think the best solution will be to allow in spawn regions to define a list of vehicle types that can be spawned there, and if a user opens the garage in that region, it will only show spawnable vehicles.

**Comment by SatireShadow** [comment]
> I think the best solution will be to allow in spawn regions to define a list of vehicle types that can be spawned there, and if a user opens the garage in that region, it will only show spawnable vehicles. 

This sadly wouldn't work for what I have now. I have a custom plugin made where I can create blocks that when placed can run any command that us admins set for players so right now people can make a garage block abd place it so it works as a a garage.

**Comment by stijnb1234** [comment]
Won't be worked in, because it's too specific, where I don't expect many people to get anything out of this. This, on the other hand, can be accomplished with the API.
