### ISSUE TITLE
VehicleUpgradeEvent

### ISSUE THREAD

**Issue by Danieljunek17** [stijnb1234/VehiclesPlus#90]
**Is your feature request related to a problem? Please describe.**  
sort of I can't check if there is executed a vehicle engine upgrade and it would be nice to grab that and execute some extra stuff

**Describe the solution you'd like**  
the VehicleUpgradeEvent with the player that clicked on the upgrade, vehicle owner, storagevehicle or spawnedvehicle and which upgrad path (Speed, Acceleration, ..)

**Describe alternatives you've considered**  
creating the api myself but I have basicly stumbled on the issue of some changes that are required in `VehicleUpgradeGUI`

**Comment by stijnb1234** [comment]
Will add this event. ;)

**Comment by stijnb1234** [comment]
Will be added in v2.3.1
