### ISSUE TITLE
Feature Request - Gear Shifts

### ISSUE THREAD

**Issue by SatireShadow** [stijnb1234/VehiclesPlus#91]
**Is your feature request related to a problem? Please describe.**  
A clear and concise description of what the problem is. Ex. I'm always frustrated when I'm driving a faster car and it uncontrollably goes pedal to the metal instead of gradual speed increase and speed balancing.

**Describe the solution you'd like**  
gear shifting where right click will make you go up a gear and left click will lower your gear, gears kind of would put speed caps on the car that is being driven and how fast or slow it can accelerate cause right now cars with a high max speed instantly go super fast and you can't control it.

**Describe alternatives you've considered**  
I've considered W/S tapping but it becomes very difficult to do.

**Additional context**

**Comment by stijnb1234** [comment]
Won't be worked on for now, because that mechanic is just too difficult for Minecraft.
