### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Akmenis** [stijnb1234/VehiclesPlus#94]
**Describe the bug**  
Plugin not loading (Version 2.3.0)

**To Reproduce**  
idk, it  is not loading

**Expected behavior**  

**Screenshots or Video Recordings**  
i don't have but it not loads (in log and commands not working)

**Server and Plugin Information**
 - Installed plugins: VehiclesPlus Pro  v2.3.0, User login, SARanks, PluginConstructorAPI, QualityArmor, ItemBridge v2, TAB, TNE, Towny, CustomNukes, ProtocolLib, Vault, TimberPlugin, TownyChat, LogBlock, Dynmap-Towny, Dynmap, Brewery, Playerkits, SetHome, XWeatherPlus, Thirst, HeadsPlus, KelpEffect, RestartCountdown, AntyXray, GSit, Jobs, MySkin, NexEngine, GoldenCrates
 - VehiclesPlus Version:
 - Pro?
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: spigot 1.16.5
 - Operating System (if applicable): Windows

**Additional context**  
LOG:https://pastebin.com/clone/hJUKRmTv . If it is possible please fix it as fast as you can.

**Comment by relavis** [comment]
Can you fill out the rest of the format so we can help you properly?

**Comment by Akmenis** [comment]
> Can you fill out the rest of the format so we can help you properly?

Now corrected

**Comment by Akmenis** [comment]
But have to wait a while cuz i updated it few seconds ago

**Comment by Akmenis** [comment]
> Can you fill out the rest of the format so we can help you properly?

Is it now okay?

**Comment by relavis** [comment]
You're missing an economy plugin like Essentials.

**Comment by Akmenis** [comment]
I've got it (TNE is TheNewEconomy)

**Comment by Akmenis** [comment]
Changet it to HyperConomy too and still not working
