### ISSUE TITLE
Add Vehicles

### ISSUE THREAD

**Issue by rikdijkslag** [stijnb1234/VehiclesPlus#97]
Hi, I can't find anywhere where I can add cars myself.
I havce this texturepack but i realy dont know where to start.
Sorry if this is the wrong topic.

Here is the texturepack
[Minetopia_Classic_CarPack_v1.16.zip](https://github.com/stijnb1234/VehiclesPlus/files/6545855/Minetopia_Classic_CarPack_v1.16.zip)

The texturepack use optifine to see all items

**Comment by stijnb1234** [comment]
No support is provided on GitHub. You can join our Discord if you want support about any of my plugins.

See also the wiki for more information: 
https://docs.volmit.com/vehiclesplus/
